version: "3.9"

services:
  app:
    image: dimaparty/app:latest
    environment:
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
      - GIT_COMMIT
      - DEPLOYED_BY=github-actions
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      retries: 3

  nginx:
    image: dimaparty/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
